### ISSUE TITLE
How to calculate the proportion of introgression?

### ISSUE THREAD

**Issue by silvewheat** [simonhmartin/tutorials#1]
Hello,
     After calculated the fd using sliding windows, how we calculate the proportion of introgressed regions arcoss the whole genomes? That is, how we determine the threshold of a introgressed window? Using top 5% and reduced dxy (also bottom 5%) ?

**Comment by simonhmartin** [comment]
Hello, I'm very sorry to have missed this question, now over a year ago!

My recommendation is not to use the fd value for windows to compute the genome-wide proportion of introgression. Instead, it would be better to compute a single genome-wide f estimate. There are tools such as [Dsuite](https://github.com/millanek/Dsuite) that can do that. Otherwise, my other [tutorial](https://github.com/simonhmartin/tutorials/tree/master/ABBA_BABA_whole_genome) shows a way to do it manually from allele frequency data.

**Comment by silvewheat** [comment]
Thanks for your answer.

Best wishes.
